<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-M8RIVEK" failures="0" tests="1" name="main.InvocationCounttest" time="1.040" errors="1" timestamp="26 Jan 2019 17:56:44 GMT" skipped="0">
  <testcase classname="main.InvocationCounttest" name="f" time="1.040">
    <error message="Method main.InvocationCounttest.f() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method main.InvocationCounttest.f() didn't finish within the time-out 1000
at java.base@11.0.1/java.lang.invoke.MethodType$ConcurrentWeakInternSet.add(MethodType.java:1318)
at java.base@11.0.1/java.lang.invoke.MethodType.makeImpl(MethodType.java:315)
at java.base@11.0.1/java.lang.invoke.MethodHandleNatives.findMethodHandleType(MethodHandleNatives.java:376)
at java.base@11.0.1/java.util.concurrent.FutureTask.setException(FutureTask.java:247)
at java.base@11.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:269)
at java.base@11.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@11.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@11.0.1/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- f -->
</testsuite> <!-- main.InvocationCounttest -->
